# Generated by Django 4.2 on 2025-01-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_email_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
