# Generated by Django 4.2 on 2024-12-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('desc', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=15)),
                ('time', models.DateTimeField()),
                ('category', models.IntegerField()),
            ],
        ),
    ]
