# Generated by Django 4.2 on 2024-12-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spends',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
