# Generated by Django 4.2 on 2024-12-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spends', '0002_alter_spends_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('name', models.CharField(max_length=25)),
            ],
        ),
    ]
