# Generated by Django 4.2 on 2024-12-25 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spends', '0003_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spends',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spends.categories'),
        ),
    ]
