# Generated by Django 4.2 on 2024-12-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spends', '0005_alter_categories_user_alter_spends_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spends',
            old_name='time',
            new_name='date',
        ),
    ]
