# Generated by Django 4.2 on 2024-12-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spends', '0006_rename_time_spends_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
