# Generated by Django 4.2 on 2025-01-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spends', '0009_alter_spends_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spends',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='spends',
            name='date',
            field=models.DateField(),
        ),
    ]
