# Generated by Django 4.2 on 2025-01-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spends', '0010_alter_spends_amount_alter_spends_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='amount_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
